apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parks-app
spec:
  destination:
    name: ''
    namespace: b-project
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/ultraJeff/parks-app-gitops'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
