# This is done via Helm in ArgoCD so just point to the root
# It sees Chart.yaml and values.yaml and templates folder and it figure it out on its own
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-parks
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    has-git-repo-objects: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    # TODO: Do we need to namespace this?
    namespace: parks-app
  source:
    repoURL: ''
    targetRevision: ''
    path: .
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: parks-app
# spec:
#   destination:
#     namespace: parks-app
#     server: 'https://kubernetes.default.svc'
#   source:
#     path: .
#     repoURL: 'https://github.com/ultraJeff/parks-app-gitops'
#     targetRevision: main
#   sources: []
#   project: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: false
#     # syncOptions:
#     #   - CreateNamespace=true