apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-operator-custom-metrics-autoscaler.yaml
  - 02-operator-kafka.yaml

  - 10-instance-custom-metrics-autoscaler.yaml
  - 11-instance-kafka.yaml

  - 20-application-parks-weather.yaml
  - 21-application-parks-backend.yaml
  - 22-application-parks-dashboard.yaml

components:
  - ../components/git-config