apiVersion: tekton.dev/v1
kind: Task
  name: apply-manifests
  namespace: a-project
spec:
  params:
    - default: k8s
      description: The directory in source that contains yaml manifests
      name: manifest_dir
      type: string
  steps:
    # - script: |
    #     #!/usr/bin/env bash
    #     echo Applying manifests in $(inputs.params.manifest_dir) directory
    #     oc apply -f $(inputs.params.manifest_dir)
    #     echo -----------------------------------
    - args:
        - |-
          echo Applying manifests in $(inputs.params.manifest_dir) directory
          oc apply -f $(inputs.params.manifest_dir)
          echo -----------------------------------
      command:
        - /bin/bash
        - '-c'
      computeResources: {}
      image: 'quay.io/openshift/origin-cli:latest'
      name: apply
      workingDir: /workspace/source
  workspaces:
    - name: source
