kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configMap.name }}
data:
  KAFKA_CLUSTER: {{ .Values.kafka.cluster }}
  PARKS_ENDPOINT: {{ .Values.endpoints.parks }}
  WEATHER_ENDPOINT: {{ .Values.endpoints.weather }}