kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configMap.name }}
data:
  # Need AMQ Streams / Kafka cluster up and named kafka (TODO: Add operator here)
  KAFKA_CLUSTER: kafka-kafka-bootstrap.openshift-operators.svc:9092
  PARKS_ENDPOINT: parks-app-park-app-gitops.parks-app.svc.cluster.local:8080
  WEATHER_ENDPOINT: parks-weather.parks-app.svc.cluster.local:8090