apiVersion: apps/v1
kind: Deployment
metadata:
  name: parks-weather
  annotations:
    app.openshift.io/connects-to: parks-app
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/ultraJeff/parks-weather'
  labels:
    app: parks-weather
    app.kubernetes.io/name: parks-weather
    app.kubernetes.io/component: event-source
    app.openshift.io/runtime: quarkus
    {{- include "parks-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: parks-weather
      name: parks-weather
  replicas: 1
  template:
    metadata:
      labels:
        name: parks-weather
        app.kubernetes.io/name: parks-weather
    spec:
      containers:
        - name: parks-weather
        #   env:
            # - name: QUARKUS_KUBERNETES_CONFIG_ENABLED
            #   value: "true"
            # - name: QUARKUS_KUBERNETES_CONFIG_CONFIG_MAPS
            #   value: server
            # - name: JAVA_OPTIONS
            #   value: >-
            #     -Dquarkus.kubernetes-config.enabled=true
            #     -Dquarkus.kubernetes-config.config-maps=server
          envFrom:
          - configMapRef:
              name: {{ .Values.configMap.name }}
          image: quay.io/jefrankl/parks-weather:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8090
            protocol: TCP
            name: http
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8090
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
              httpGet:
                path: /q/health/ready
                port: 8090
                scheme: HTTP
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
