kind: Service
apiVersion: v1
metadata:
  name: parks-weather
  labels:
    app: parks-weather
    app.kubernetes.io/component: event-source
    app.kubernetes.io/name: parks-weather
    app.openshift.io/runtime: quarkus
    {{- include "parks-app.labels" . | nindent 4 }}
spec:
  ports:
    - name: 8090-tcp
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: parks-weather
    deployment: parks-weather